services:
  temp:
    build:
      context: dockerfiles
      dockerfile: vllm.Dockerfile
    entrypoint: bash
    volumes:
      - ./models:/models

  vllm:
    image: vllm/vllm-openai:v0.7.3
    entrypoint: python3 -m vllm.entrypoints.openai.api_server
      --model /models/Qwen2.5-0.5B-Instruct
      --served-model-name ChatBot
      --gpu-memory-utilization 0.80
      --disable-log-requests
      --enable-prefix-caching
      --dtype half
    volumes: 
      - ./models:/models
    environment:
      VLLM_USE_V1: 0
      VLLM_ATTENTION_BACKEND: "FLASH_ATTN"
    ports:
      - "5000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - llm-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]  
  webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "open-webui:/app/backend/data"
    environment:
      ENABLE_OLLAMA_API: false
      ENABLE_RAG_WEB_SEARCH: true
      RAG_WEB_SEARCH_ENGINE: "duckduckgo"
      DEFAULT_MODELS: "ChatBot"
      DEFAULT_USER_ROLE: "user"
      OPENAI_API_BASE_URL: "http://vllm:8000/v1"
    networks:
      - llm-network

networks:
  llm-network:
    driver: bridge
