services:
  temp:
    build:
      context: dockerfiles
      dockerfile: vllm.Dockerfile
    entrypoint: bash
    volumes:
      - ./models:/models

  vllm:
    image: vllm/vllm-openai:v0.7.3
    container_name: $COMPOSE_PROJECT_NAME-engine
    entrypoint: python3 -m vllm.entrypoints.openai.api_server
      --model /models/$MODEL_NAME
      --served-model-name $SERVED_MODEL_NAME
      --gpu-memory-utilization $GPU_MEMORY_UTILIZATION
      --disable-log-requests
      --enable-prefix-caching
      --dtype half
    volumes: 
      - ./models:/models
    environment:
      VLLM_USE_V1: 0
      VLLM_ATTENTION_BACKEND: "FLASH_ATTN"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - llm-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]  
  webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: $COMPOSE_PROJECT_NAME-webui
    ports:
      - "$WEBUI_PORT:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./open-webui:/app/backend/data"
    environment:
      ENABLE_OLLAMA_API: false
      ENABLE_RAG_WEB_SEARCH: true
      RAG_WEB_SEARCH_ENGINE: "duckduckgo"
      DEFAULT_MODELS: $SERVED_MODEL_NAME
      DEFAULT_USER_ROLE: "user"
      OPENAI_API_BASE_URL: "http://vllm:8000/v1"
    networks:
      - llm-network

networks:
  llm-network:
    driver: bridge
